config/routes.rb
Rails.application.routes.draw do
  resources :submitted_answers
  resources :answers
  resources :questions
  resources :categories
  root 'static_page#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submitted_answer.rb
class SubmittedAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/submitted_answers_controller.rb
class SubmittedAnswersController < ApplicationController
  before_action :set_submitted_answer, only: [:show, :edit, :update, :destroy]

  # GET /submitted_answers
  # GET /submitted_answers.json
  def index
    @submitted_answers = SubmittedAnswer.all
  end

  # GET /submitted_answers/1
  # GET /submitted_answers/1.json
  def show
  end

  # GET /submitted_answers/new
  def new
    @submitted_answer = SubmittedAnswer.new
  end

  # GET /submitted_answers/1/edit
  def edit
  end

  # POST /submitted_answers
  # POST /submitted_answers.json
  def create
    @submitted_answer = SubmittedAnswer.new(submitted_answer_params)
    @question = Question.find_by_id(submitted_answer_params[:question_id])
    if @question.answers.first.name.downcase == @submitted_answer.answer.downcase
      @submitted_answer.score = 4
    else
      @submitted_answer.score = -1
    end

    respond_to do |format|
      if @submitted_answer.save
        format.html { redirect_to @question, notice: 'Submitted answer was successfully created.' }
        format.json { render :show, status: :created, location: @submitted_answer }
      else
        format.html { render :new }
        format.json { render json: @submitted_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submitted_answers/1
  # PATCH/PUT /submitted_answers/1.json
  def update
    respond_to do |format|
      if @submitted_answer.update(submitted_answer_params)
        format.html { redirect_to @submitted_answer, notice: 'Submitted answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @submitted_answer }
      else
        format.html { render :edit }
        format.json { render json: @submitted_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submitted_answers/1
  # DELETE /submitted_answers/1.json
  def destroy
    @submitted_answer.destroy
    respond_to do |format|
      format.html { redirect_to submitted_answers_url, notice: 'Submitted answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submitted_answer
      @submitted_answer = SubmittedAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submitted_answer_params
      params.require(:submitted_answer).permit(:user_id, :question_id, :answer, :score)
    end
end

app/helpers/submitted_answers_helper.rb
module SubmittedAnswersHelper
end

app/views/submitted_answers/_form.html.slim
= form_for @submitted_answer do |f|
  - if @submitted_answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@submitted_answer.errors.count, "error")} prohibited this submitted_answer from being saved:"
      ul
        - @submitted_answer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :answer
    = f.text_field :answer
  .field
    = f.label :score
    = f.number_field :score
  .actions = f.submit

app/views/submitted_answers/edit.html.slim
h1 Editing submitted_answer

== render 'form'

= link_to 'Show', @submitted_answer
'  |
= link_to 'Back', submitted_answers_path

app/views/submitted_answers/index.html.slim
h1 Listing submitted_answers

table
  thead
    tr
      th User
      th Question
      th Answer
      th Score
      th
      th
      th

  tbody
    - @submitted_answers.each do |submitted_answer|
      tr
        td = submitted_answer.user
        td = submitted_answer.question
        td = submitted_answer.answer
        td = submitted_answer.score
        td = link_to 'Show', submitted_answer
        td = link_to 'Edit', edit_submitted_answer_path(submitted_answer)
        td = link_to 'Destroy', submitted_answer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Submitted answer', new_submitted_answer_path

app/views/submitted_answers/new.html.slim
h1 New submitted_answer

== render 'form'

= link_to 'Back', submitted_answers_path

app/views/submitted_answers/show.html.slim
p#notice = notice

p
  strong User:
  = @submitted_answer.user
p
  strong Question:
  = @submitted_answer.question
p
  strong Answer:
  = @submitted_answer.answer
p
  strong Score:
  = @submitted_answer.score

= link_to 'Edit', edit_submitted_answer_path(@submitted_answer)
'  |
= link_to 'Back', submitted_answers_path