config/routes.rb
Rails.application.routes.draw do
  resources :submitted_answers
  resources :answers
  resources :questions
  resources :categories
  root 'static_page#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:name, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.slim
= form_for @answer do |f|
  - if @answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :question
    = f.text_field :question
  .actions = f.submit

app/views/answers/edit.html.slim
h1 Editing answer

== render 'form'

= link_to 'Show', @answer
'  |
= link_to 'Back', answers_path

app/views/answers/index.html.slim
h1 Listing answers

table
  thead
    tr
      th Name
      th Question
      th
      th
      th

  tbody
    - @answers.each do |answer|
      tr
        td = answer.name
        td = answer.question
        td = link_to 'Show', answer
        td = link_to 'Edit', edit_answer_path(answer)
        td = link_to 'Destroy', answer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.slim
h1 New answer

== render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.slim
p#notice = notice

p
  strong Name:
  = @answer.name
p
  strong Question:
  = @answer.question

= link_to 'Edit', edit_answer_path(@answer)
'  |
= link_to 'Back', answers_path