config/routes.rb
Rails.application.routes.draw do
  resources :submitted_answers
  resources :answers
  resources :questions
  resources :categories
  root 'static_page#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Play Game', questions_path, class: 'navbar-brand'
      = link_to 'Create Question', new_question_path, class: 'navbar-brand'
      = link_to 'Categories', categories_path, class: 'navbar-brand'
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li
          = link_to 'Sign out', destroy_user_session_path, class: 'navbar-brand pull-right', method: :delete
      - else
        li
          = link_to 'Sign in', new_user_session_path, class: 'navbar-brand pull-right'
          = link_to 'Sign up', new_user_registration_path, class: 'navbar-brand pull-right'
      end
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Trivia Game'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Basic Setup'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == yield